language: node_js
node_js:
  - "5"
  - "4"
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - npm install -g electron-prebuilt
  - npm install -g electron-mocha
notifications:
  email:
    on_success: never
    on_failure: change
